### PR TITLE
[TEST]Support Single Policyfile

### PR DESCRIPTION
**Pull request by sawanoboly**
Ref: #79

### CODE REVIEW

**Comment by sawanoboly** [comment]
## Setup

1. add lines to knife.rb

```
use_policyfile true
versioned_cookbooks true
policy_document_native_api false
```

2. create `Policyfile.lock.json`

`chef install / chef update`

3. export policy

`chef export ./ -f`

creates

- cookbooks
- data_bags/ policyfiles

deployment_group is `${policyname}-local`.

## Run

### bootstrap

```
knife zero bootstrap --policy-name build HOST_NAME -N NODE_NAME
```

### converge

```
knife zero converge "name:NODE_NAME"
```

or

```
knife zero converge -n NAMED_RUNLIST  "name:NODE_NAME"
```

**Comment by epcim** [comment]
Works great! Splendid!

For others, don't just copy & paste. As of chef-client >= 12.7.x  the compatibility mode has been removed / deprecated.  Since v1.14.0 from #85 which implement policyfiles native API there is no need for it. Just make sure you run with:
```
policy_document_native_api true # (or avoid as it's probably default).
```

@sawanoboly will post you soon some notes or PR to docs for CLI usage with chef-repo (policybased). I have seen the knife-zero docs regarding and policyfiles, knife serve/chef push is great, but have to find smooth path for daily usage. (for single, export -f is actually tricky while used on chef-repo, it replaces whole directories .chef, policies).

**Comment by sawanoboly** [comment]
@epcim Thank you for trial :smiley:  

I agree that current workflows are little tricky for daily use. But, I don't have good idea for it yet.

Probably, adding local-mode (boot up chef-zero automatically.) to the chef-dk is simple way I think.

**Comment by epcim** [comment]
@sawanoboly well I today deployed a couple of nodes using knife-zero. All things went pretty smooth. As I  am using chef repo with policy files, the only option is to for multiple policices. I am using another knife-push.rb config for push and the `knife serve --chef-zero-port 8989`. 

```
use_policyfile true
versioned_cookbooks true
policy_document_native_api true

chef_server_url "http://localhost:8989"

node_name ENV['USER'] || 'provisioner'
local_mode true

```

It may run in the other terminal in the background but still it's bit confusing. As basically all you want is "berks vendor" use case. And the fact that "cookbook_artefacts" and policyfiles/*.json generated by push are more or less "rubbish" for the repo directory itself in the "knife-zero local mode". Best to keep them separate.

Would be nice if the `chef export -f` would allow multiple policies mode byt that's another story.

All that comes to what you suggest. "boot-up chef-zero automatically". All you need is the same what "berks vendor" does. Publish artifacts for later usage. How about to start it in background against <repo>/.zero or <repo>/.chef/.zero folder with the functionality of zero-repo. In general the behavior is the same what "chef export .chef/.zero -f" does (or similarly as test-kitchen has  persistent storage for VMs). Then create in that folder .chef/knife.rb with the configuration to point a data_bag, client, nodes folder in main repo. an in the .zero keep "cookbook_artifacts", "policies", "policy_groups", etc..

Assuming we are using "knife-zero" for single shoot deployments, CI, server-less workflow. There is no need to fire "chef install & update" chef push in multiple commands as it's what's tricky, all you actually need is to "chef push the facts". So:
```
knife zero push [--update] [policies/gitlab.rb]
```
is probably the most frequent usage, where it would do:
- run chef install (optionally --update) the policy in <repo>
- start "knife serve" against properly configured .zero folder, if not running
- start "knife push" against properly configured .zero folder
- stop knife serve with some reasonable delay

with no policy specified it would process all in `policies/*.rb`.
knife zero converge/boostrap is supposed to use .zero folder to search for cookbooks, etc

**Comment by sawanoboly** [comment]
@epcim 

Thank you for report which based on real workflow. 

I don't have much time for consider it currently.But, I have plans of deployment new infrastructure for me soon. And I'm going to use policyfile to it.
I'll consider how to use more smoothly than current usage at that time. Of couse, I will use your suggestion as reference.

**Pull request merged**
